recipe: default.v1
language: en
pipeline:
- name: WhitespaceTokenizer
- name: EntitySynonymMapper
- name: RegexFeaturizer
- name: CRFEntityExtractor
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 100
  model_confidence: softmax
  constrain_similarities: true
- name: FallbackClassifier
  threshold: 0.3
  tables:
  - job_title.yml

policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: UnexpecTEDIntentPolicy
  max_history: 10
  epochs: 100
- name: TEDPolicy
  max_history: 10
  epochs: 100
  constrain_similarities: true
 

assistant_id: 20230410-093831-plain-headset
